config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  match '/contacts', to: 'contacts#new', via: 'get'
	resources "contacts", only: [:new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :sku, length: { is: 6 }
	validates :category, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products_grid = initialize_grid(Product)
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			flash[:success] = "Product updated"
			redirect_to(:action=>'index')
		else
			flash[:success] = "Incorrect information provided, please try again."
			redirect_to(:action=>'edit')
		end
	end

	private

	def product_params
		params.require(:product).permit(:name, :sku, :category)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="/">Home</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Wiser Code Challenge</h3>
      </div>

      <h4>Edit Product</h4>
      <%= simple_form_for @product do |f| %>
      <%= f.input :name %>
      <%= f.input :sku %>
      <%= f.input :category %>
      <%= f.button :submit %>
      <% end %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>



    

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <h3 class="text-muted">Wiser Code Challenge</h3>
      </div>

      <div class="jumbotron">
        <h1>Products</h1>
        <p class="lead">Search and edit</p>
      </div>

      <%= grid(@products_grid, show_filters: :always) do |g|

          g.column name: 'ID', attribute: 'id' do |product|
            product.id
          end

          g.column name: 'Name', attribute: 'name' do |product|
            product.name
          end

          g.column name: 'sku', attribute: 'sku' do |product|
            product.sku
          end

          g.column name: 'Category', attribute: 'category' do |product|
            product.category
          end

          g.column do |product|
            link_to('Edit', edit_product_path(product))
          end
        end -%>

      <footer class="footer">
        <p>&copy; Casie Levine Submission October 14, 2015</p>
      </footer>

    </div> <!-- /container -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>